server:
 port: 9091
 
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
  eureka-server-read-timeout-seconds: 500

 instance:
  hostname: localhost
 register-with-eureka: true
 fetch-registry: true
 
 
  
 
